Treemap + Sunburst
dataiku/dss-plugin-hierarchical-charts pull request #1
Opened 2019-07-02 22:58 UTC by du-phan

2019-07-29 10:03 UTC, JoachimZ requested changes
Why columns on the left, not on top? To spare vertical space?
Error reporting does not seem correct, make sure the user has feedback when webapp backend fails (for any reason)
I can probably make a few more comment.

2019-07-29 10:03 UTC, JoachimZ commented on plugin.json
> +        "description": "",
"Treemap and Sunburst plugin charts"

2019-07-29 10:03 UTC, JoachimZ commented on plugin.json
> +    "id": "dss-plugin-hierarchical-charts",
hierarchical-charts

2019-07-29 10:03 UTC, JoachimZ commented on plugin.json
> +        "url": "https://www.dataiku.com/dss/plugins/info/google-charts.html",
https://www.dataiku.com/dss/plugins/info/hierarchical-charts.html

2019-07-29 10:03 UTC, JoachimZ commented on webapps/sunburst-chart/app.js
> +var width = 350;
tiny detail, I would avoid ever using "var" use "let" or "const" instead, it avoids a few bugs sometimes. It's really not much but it does not cost anything...

2019-07-29 10:03 UTC, JoachimZ commented on webapps/sunburst-chart/app.js
> +    // For efficiency, filter nodes to keep only those large enough to see.
Nice! (0.29 degree seems small but I did not check yet)

2019-07-29 10:03 UTC, JoachimZ commented on webapps/sunburst-chart/app.js
> +    })(nodes);
Mwarf, it seems correct but circumvoluted :D 

`const uniqueNames = Array.from(new Set(nodes.map(n => n.name)))`
or 
`const uniqueNames = [...new Set(nodes.map(n => n.name))]`
or 
```
function unique(arr) {
    return [...new Set(arr)];
}
const uniqueNames = unique(nodes.map(n => n.name));
```

2019-07-29 10:03 UTC, JoachimZ commented on webapps/sunburst-chart/webapp.json
> +        "description": "",
Visualize hierarchies as concentric circles

2019-07-29 10:03 UTC, JoachimZ commented on webapps/sunburst-tree/app.js
> +    })(nodes);
same as above

2019-07-29 10:03 UTC, JoachimZ commented on webapps/sunburst-chart/webapp.json
> +        "label": "Sunburst chart",
Just "Sunburst"

2019-07-29 10:03 UTC, JoachimZ commented on webapps/sunburst-tree/webapp.json
> +        "label": "Sunburst tree",
Just "Sunburst"

2019-07-29 10:03 UTC, JoachimZ commented on webapps/treemap-chart/body.html
> +<script src="/plugins/dss-plugin-hierarchical-charts/resource/treemap-chart.js"></script>
does not exist, right?

2019-07-29 10:03 UTC, JoachimZ commented on webapps/treemap-chart/style.css
> +@import '/plugins/dss-plugin-hierarchical-charts/resource/style.css';
update without dss-plugin

2019-07-29 10:03 UTC, JoachimZ commented on Makefile
> +PLUGIN_ID=dss-plugin-hierarchical-charts
update without dss-plugin

2019-07-29 10:03 UTC, JoachimZ commented on webapps/sunburst-chart/body.html
> +<script src="/plugins/dss-plugin-hierarchical-charts/resource/dku-helpers.js"></script>
update without dss-plugin

2019-07-29 10:03 UTC, JoachimZ commented on webapps/sunburst-chart/style.css
> +@import '/plugins/dss-plugin-hierarchical-charts/resource/style.css';
update without dss-plugin

2019-07-29 10:03 UTC, JoachimZ commented on webapps/sunburst-tree/body.html
> +<script src="/plugins/dss-plugin-hierarchical-charts/resource/dku-helpers.js"></script>
update without dss-plugin

2019-07-29 10:03 UTC, JoachimZ commented on webapps/sunburst-tree/style.css
> +@import '/plugins/dss-plugin-hierarchical-charts/resource/style.css';
update without dss-plugin

2019-07-29 10:03 UTC, JoachimZ commented on webapps/treemap-chart/body.html
> +<script src="/plugins/dss-plugin-hierarchical-charts/resource/dku-helpers.js"></script>
update without dss-plugin

2019-07-29 14:47 UTC, du-phan commented
I made all the modifications according to Joachim's review

2019-07-29 14:49 UTC, du-phan commented
> Why columns on the left, not on top? To spare vertical space?

Yes so that we have places for the rules dropdown

2019-07-31 07:46 UTC, cperdigou commented
Tested and reviewed, very nice 👍

2019-07-31 07:46 UTC, merged